#version: '3'
#services:
#  mysql-standalone:
#    image: 'mysql:8.0.30'
#    environment:
#      - MYSQL_ROOT_PASSWORD=0405
#      - MYSQL_PASSWORD=0405
#      - MYSQL_DATABASE=exercising
#    ports:
#      - "3307:3306"
#  springboot-docker-container:
#    image: springboot-docker-container
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/demo?autoReconnect=true&useSSL=false
#      SPRING_DATASOURCE_USERNAME: "root"
#      SPRING_DATASOURCE_PASSWORD: "root"
#    build:
#      context: "./"
#      dockerfile: "DockerFile"
#    depends_on:
#      - mysql-standalone